"use client";

import React from "react";
import { Download, Terminal } from "lucide-react";
import { 
  Box, Typography, Button, Container, Card, CardContent, Alert, AlertTitle
} from "@mui/material";

export default function DownloadPage() {
  return (
    <Box sx={{ p: { xs: 2, md: 4 }, pt: { xs: 2, md: 2 } }}>
      <Container maxWidth="md" sx={{ px: 0 }}>
        <Box sx={{ pb: 3, borderBottom: 1, borderColor: 'divider', display: 'flex', flexDirection: { xs: 'column', md: 'row' }, justifyContent: 'space-between', alignItems: { xs: 'flex-start', md: 'center' }, gap: 3 }}>
          <Box>
            <Typography variant="h4"  sx={{ fontWeight: 'bold' }}>AutoCAD Integration</Typography>
            <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
              Bridge the gap between RDCAD Express and your local AutoCAD environment.
            </Typography>
          </Box>
          <Button 
            component="a"
            href="/rdcad-import.lsp"
            download="rdcad-import.lsp"
            variant="contained"
            color="primary"
            startIcon={<Download size={20} />}
            sx={{ px: 3, py: 1.5, borderRadius: 2 }}
          >
            Download Script (.lsp)
          </Button>
        </Box>

        <Card variant="outlined" sx={{ mt: 4, borderRadius: 4 }}>
          <CardContent sx={{ p: { xs: 3, md: 5 }, display: 'flex', flexDirection: 'column', gap: 4 }}>
            <Box>
              <Typography variant="h5"  sx={{ fontWeight: 'bold',  mb: 2 }}>How it works</Typography>
              <Typography color="text.secondary" sx={{ fontSize: '1.1rem', lineHeight: 1.6 }}>
                Downloading DXF files is only half the battle. To truly speed up your workflow, we&apos;ve created a tiny (1KB) AutoLISP companion script. When executed, this script instantly locates the most recent DXF file in your Downloads folder and attaches it to your cursor for immediate insertion into your drawing.
              </Typography>
            </Box>
            
            <Alert severity="info" variant="outlined" sx={{ borderRadius: 2 }}>
              <AlertTitle sx={{ fontWeight: 'bold' }}>Compatibility Note</AlertTitle>
              <Typography variant="body2" sx={{ mt: 1, mb: 1 }}>
                <strong>DXF Files:</strong> The .dxf files generated by RDCAD Express are universally supported and can be opened in <em>any</em> CAD software (AutoCAD, MicroStation, FreeCAD, etc.).
              </Typography>
              <Typography variant="body2">
                <strong>LISP Script:</strong> This script works perfectly in AutoCAD, as well as AutoCAD alternatives that support AutoLISP (like BricsCAD, ZWCAD, and GstarCAD). For other software, simply drag and drop the DXF file into your workspace!
              </Typography>
            </Alert>

            <Box>
              <Typography variant="h6"  sx={{ fontWeight: 'bold',  mb: 3 }}>Installation & Usage</Typography>
              <Box component="ol" sx={{ pl: 2, m: 0, '& li': { mb: 2, color: 'text.secondary' } }}>
                <Typography component="li" variant="body1">
                  <Typography component="span" color="text.primary">Download the script</Typography> using the button above.
                </Typography>
                <Typography component="li" variant="body1">
                  <Typography component="span" color="text.primary">Drag and drop</Typography> the downloaded <Box component="code" sx={{ px: 1, py: 0.5, bgcolor: 'action.hover', borderRadius: 1, color: 'primary.main', fontFamily: 'monospace' }}>rdcad-import.lsp</Box> file directly into your open AutoCAD window to load it for the current session.
                </Typography>
                <Typography component="li" variant="body1">
                  Type <Box component="code" sx={{ px: 1, py: 0.5, bgcolor: 'action.hover', borderRadius: 1, color: 'success.main', fontFamily: 'monospace' }}>RDCAD_IMPORT</Box> in the AutoCAD command line and press Enter.
                </Typography>
                <Typography component="li" variant="body1">
                  The newest <Box component="code" sx={{ fontFamily: 'monospace' }}>.dxf</Box> file from your Downloads folder will instantly appear on your cursor. Click to place!
                </Typography>
              </Box>
            </Box>

            <Box sx={{ p: 3, bgcolor: 'background.default', borderRadius: 2, border: 1, borderColor: 'divider' }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1.5, color: 'text.secondary' }}>
                <Terminal size={18} />
                <Typography variant="subtitle2"  sx={{ fontWeight: 'bold' }}>Pro Tip: Persistent Loading</Typography>
              </Box>
              <Typography variant="body2" color="text.secondary">
                To avoid dragging and dropping the file every time you open AutoCAD, you can add it to your <strong>Startup Suite</strong>. Type <Box component="code" sx={{ px: 1, py: 0.5, bgcolor: 'action.hover', borderRadius: 1, color: 'text.primary', fontFamily: 'monospace' }}>APPLOAD</Box> in AutoCAD, click the &quot;Contents...&quot; button under the Startup Suite section, and add the <Box component="code" sx={{ px: 1, py: 0.5, bgcolor: 'action.hover', borderRadius: 1, color: 'primary.main', fontFamily: 'monospace' }}>rdcad-import.lsp</Box> file there.
              </Typography>
            </Box>
          </CardContent>
        </Card>
      </Container>
    </Box>
  );
}
