"use client";

import React from "react";
import { Download, Terminal } from "lucide-react";

export default function DownloadPage() {
  return (
    <div className="p-8">
      <div className="max-w-4xl mx-auto space-y-8">
        <header className="flex flex-col md:flex-row md:justify-between items-start md:items-center gap-4 pb-6 border-b border-slate-800">
          <div>
            <h1 className="text-3xl font-bold text-white">AutoCAD Integration</h1>
            <p className="text-slate-400 mt-2">Bridge the gap between RDCAD Express and your local AutoCAD environment.</p>
          </div>
          <a 
            href="/rdcad-import.lsp" 
            download="rdcad-import.lsp"
            className="flex items-center gap-2 px-6 py-3 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg font-medium transition shadow-lg shadow-indigo-500/20"
          >
            <Download className="w-5 h-5" /> Download Script (.lsp)
          </a>
        </header>

        <div className="bg-slate-900 rounded-xl border border-slate-800 p-8 space-y-6">
          <h2 className="text-2xl font-semibold text-white">How it works</h2>
          <p className="text-slate-400 text-lg leading-relaxed">
            Downloading DXF files is only half the battle. To truly speed up your workflow, we've created a tiny (1KB) AutoLISP companion script. When executed, this script instantly locates the most recent DXF file in your Downloads folder and attaches it to your cursor for immediate insertion into your drawing.
          </p>
          
          <div className="bg-blue-900/20 border border-blue-500/20 p-4 rounded-lg">
            <h4 className="text-blue-400 font-medium mb-1">Compatibility Note</h4>
            <p className="text-sm text-slate-300">
              <strong>DXF Files:</strong> The .dxf files generated by RDCAD Express are universally supported and can be opened in <em>any</em> CAD software (AutoCAD, MicroStation, FreeCAD, etc.).<br/>
              <strong>LISP Script:</strong> This script works perfectly in AutoCAD, as well as AutoCAD alternatives that support AutoLISP (like BricsCAD, ZWCAD, and GstarCAD). For other software, simply drag and drop the DXF file into your workspace!
            </p>
          </div>

          <div className="space-y-4 pt-4">
            <h3 className="text-xl font-medium text-slate-200">Installation & Usage</h3>
            <ol className="list-decimal list-inside space-y-4 text-slate-400">
              <li>
                <span className="text-slate-300">Download the script</span> using the button above.
              </li>
              <li>
                <span className="text-slate-300">Drag and drop</span> the downloaded <code className="px-1.5 py-0.5 bg-slate-800 rounded text-indigo-300">rdcad-import.lsp</code> file directly into your open AutoCAD window to load it for the current session.
              </li>
              <li>
                Type <code className="px-1.5 py-0.5 bg-slate-800 rounded text-emerald-300">RDCAD_IMPORT</code> in the AutoCAD command line and press Enter.
              </li>
              <li>
                The newest `.dxf` file from your Downloads folder will instantly appear on your cursor. Click to place!
              </li>
            </ol>
          </div>

          <div className="mt-8 p-4 bg-slate-950 rounded-lg border border-slate-800">
            <div className="flex items-center gap-2 mb-2 text-slate-500 text-sm">
              <Terminal className="w-4 h-4" /> Pro Tip: Persistent Loading
            </div>
            <p className="text-sm text-slate-400">
              To avoid dragging and dropping the file every time you open AutoCAD, you can add it to your <strong>Startup Suite</strong>. Type <code className="px-1.5 py-0.5 bg-slate-800 rounded text-slate-300">APPLOAD</code> in AutoCAD, click the "Contents..." button under the Startup Suite section, and add the <code className="px-1.5 py-0.5 bg-slate-800 rounded text-indigo-300">rdcad-import.lsp</code> file there.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
